version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY:-bookclubapi}/api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/api/Dockerfile
  web:
    image: ${DOCKER_REGISTRY:-bookclubapi}/web:${TAG:-latest}
    build:
      context: .
      dockerfile: src/web/Dockerfile
  app:
    image: ${DOCKER_REGISTRY:-bookclubapi}/app:${TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile