version: '3.4'

services:
  library.unittests:
    image: ${DOCKER_REGISTRY-}lanrecontextlibraryunittests
    build:
      context: .
      dockerfile: tests/Lanre.Context.Library.UnitTests/Dockerfile

